'use  client';
import { useEffect } from 'react';
import Head from 'next/head';
import Header from '@/components/header/header'
import Cusor from '../components/customCursor';
import scroll from '@/animation/scroll';

export default function Home() {
  useEffect(() => {
    scroll()
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Cusor />
      </main>
    </>
  )
}
